### ISSUE TITLE
Module và tool không khớp

### ISSUE THREAD

**Issue by luunguyenthanhvu** [luunguyenthanhvu/ProjectAnToanThongTin#9]
- Phần mã hóa và giải mã module và tool khác nhau sửa gấp 
![420074099_907434487599686_5673320627716356839_n](https://github.com/user-attachments/assets/84cafe29-c228-4f88-90db-2feea595d452)

**Comment by tuan0919** [comment]
> * Phần mã hóa và giải mã module và tool khác nhau sửa gấp
>   ![420074099_907434487599686_5673320627716356839_n](https://private-user-images.githubusercontent.com/96241905/395773010-84cafe29-c228-4f88-90db-2feea595d452.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODIyNTYsIm5iZiI6MTczNDE4MTk1NiwicGF0aCI6Ii85NjI0MTkwNS8zOTU3NzMwMTAtODRjYWZlMjktYzIyOC00Zjg4LTkwZGItMmZlZWE1OTVkNDUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEzMTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NGExYzM2YWQ5YWE0OTAyZWNmZWMzMGVmZWYxZjg2NWQyNGJlNDc2ZjRlZWMwZjNjZDUwNmFkYjkxY2M3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yvm8uIYYW9Nwv1zeIMj2bNbypGRBhMx9h0w21OzlXso)

![image](https://github.com/user-attachments/assets/675a5598-20bf-4c82-a027-03d1c0aa48aa)
stfu,
